name: Deploy to Hostinger

on:
  push:
    branches: [ main ]

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          server-dir: ../domains/uicobe.com/public_html/exsit/wp-content/plugins/exsit-helper/
          exclude: |
            .git*
            .github/**
            .vscode/**
            node_modules/**